# Generated by Django 4.1.7 on 2023-04-09 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=255, verbose_name='Возрастная группа')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='AllTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_index=True, max_length=20, verbose_name='Рабочее время')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый клиент'), ('refusal', 'Отказ'), ('recorded', 'Записан')], default='new', max_length=255, verbose_name='Статус клиента')),
                ('status_operator', models.CharField(choices=[('not_check', 'Не проверен'), ('checked_upload', 'Проверен, записан'), ('checked_closed', 'Проверен, отказ')], default='not_check', max_length=255, verbose_name='Статус оператора')),
                ('status_coach', models.CharField(choices=[('recorded', 'Записан'), ('not_checked', 'Не проверен'), ('not_recorded', 'Отказ')], default='not_checked', max_length=255, verbose_name='Статус проверки тренера')),
                ('payed_status', models.CharField(choices=[('paid', 'Оплачен'), ('notpaid', 'Не оплачен'), ('pause', 'Пауза'), ('first', 'Первая тренировка'), ('part', 'Частичная оплата'), ('one_paid', 'Поразово'), ('this_month', 'Долг свыше месяца'), ('new_client', 'Новый клиент')], default='notpaid', max_length=255, verbose_name='Статус оплаты')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=100, unique=True, verbose_name='Номер телефона')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления клиента')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных')),
                ('payed_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255, verbose_name='День')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(max_length=255, verbose_name='Название группы')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Место тренировки')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='Тип секции')),
                ('key', models.CharField(max_length=255, verbose_name='Значение')),
            ],
        ),
        migrations.CreateModel(
            name='OtherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Локации которые были выбраны')),
                ('section', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Секции которое были выбраны')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients')),
            ],
        ),
        migrations.CreateModel(
            name='NewClientCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='FormClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Локации которые были выбраны')),
                ('visit_time', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Время которое было выбрано')),
                ('section', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Секции которое были выбраны')),
                ('age', models.CharField(max_length=100, verbose_name='Возрастная категория')),
                ('visit_day', models.CharField(max_length=1000, verbose_name='Дни которое было выбрано')),
                ('class_type', models.CharField(max_length=100, verbose_name='Тип занятий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients')),
            ],
        ),
        migrations.CreateModel(
            name='CoachForClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.CharField(max_length=255, verbose_name='Время посещения тренировки с тренером')),
                ('group_type', models.CharField(max_length=255, verbose_name='Тип тренировки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients')),
            ],
        ),
    ]
