# Generated by Django 4.2 on 2023-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_otherdata_client_alter_otherdata_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='age',
            options={'verbose_name': 'Возрастная группа', 'verbose_name_plural': 'Возрастные группы'},
        ),
        migrations.AlterModelOptions(
            name='alltime',
            options={'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочие времена'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Место тренировки', 'verbose_name_plural': 'Места тренировки'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Тип секции', 'verbose_name_plural': 'Типы секций'},
        ),
        migrations.AlterField(
            model_name='section',
            name='key',
            field=models.CharField(db_index=True, help_text='В случае добавления новой секции необходимо соблюдать формат ключей, для Йоги - "yoga_sec_ЧИСЛО", для Единоборств - "mat_sec_ЧИСЛО"', max_length=255, unique=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Тип секции'),
        ),
    ]
