# Generated by Django 4.2 on 2023-04-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_age_options_alter_alltime_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classattendance',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='coachforclient',
            options={'verbose_name': 'Тренер/Клиент', 'verbose_name_plural': 'Тренеры/Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='days',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='formclient',
            options={'verbose_name': 'Форма клиента', 'verbose_name_plural': 'Формы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'Тип группы', 'verbose_name_plural': 'Типы групп'},
        ),
        migrations.AlterModelOptions(
            name='newclientcoach',
            options={'verbose_name': 'Тренер/Клиент (Временная таблица)', 'verbose_name_plural': 'Тренеры/Клиенты (Временная таблица)'},
        ),
        migrations.AlterModelOptions(
            name='otherdata',
            options={'verbose_name': 'Форма с нестандартными данными', 'verbose_name_plural': 'Формы с нестандартными данными'},
        ),
        migrations.RemoveField(
            model_name='clients',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='name',
        ),
        migrations.AddField(
            model_name='clients',
            name='fullname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия Имя'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='classattendance',
            name='visit',
            field=models.BooleanField(default=False, verbose_name='Посещение'),
        ),
        migrations.AlterField(
            model_name='formclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients', verbose_name='Клиент'),
        ),
    ]
