# Generated by Django 4.2 on 2023-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_classattendance_options_alter_clients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachforclient',
            name='visit_day',
            field=models.CharField(default=1, max_length=255, verbose_name='Дни посещения тренировки с тренером'),
            preserve_default=False,
        ),
    ]
