# Generated by Django 4.2 on 2023-04-23 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0010_alter_formclient_location_alter_formclient_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachforclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='coachforclient',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
    ]
