# Generated by Django 4.2 on 2023-04-23 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_coachforclient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients', verbose_name='Клиент'),
        ),
    ]
