# Generated by Django 4.2 on 2023-04-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_classattendance_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formclient',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.age', verbose_name='Возрастная категория(ID)'),
        ),
        migrations.AlterField(
            model_name='formclient',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.grouptype', verbose_name='Тип занятий(ID)'),
        ),
    ]
