# Generated by Django 4.2 on 2023-04-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_formclient_age_alter_formclient_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachforclient',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.age', verbose_name='Возрастная категория'),
        ),
        migrations.AlterField(
            model_name='coachforclient',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.grouptype', verbose_name='Тип тренировки'),
        ),
    ]
