# Generated by Django 4.2 on 2023-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_coachforclient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formclient',
            name='section',
            field=models.ManyToManyField(blank=True, to='crm.section', verbose_name='Секции которые были выбраны(ID)'),
        ),
        migrations.AlterField(
            model_name='formclient',
            name='visit_day',
            field=models.ManyToManyField(to='crm.days', verbose_name='Дни которые были выбраны(ID)'),
        ),
    ]
