# Generated by Django 4.1.7 on 2023-04-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.CharField(blank=True, choices=[('empty', 'Отсутствует'), ('yoga', 'Тренер йоги'), ('martialarts', 'Тренер единоборств')], default='empty', max_length=255, null=True, verbose_name='Секция тренера'),
        ),
    ]
