# Generated by Django 4.2 on 2023-04-16 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_options_alter_user_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivatetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user', 'Пользователь'), ('coach', 'Тренер'), ('head_coach', 'Старший тренер'), ('operator', 'Оператор')], default='user', max_length=20, verbose_name='Тип профиля'),
        ),
    ]
